version: "3"

services:
  app:
    container_name: nodejs-app
    build: .
    ports:
      - '3031:3000'
    volumes:
      - .:/usr/src/app
    links:
      - mongo
    networks: 
      - nodejs-network
        
  mongo:
    container_name: nodejs-mongodb
    image: mongo
    ports:
      - '27017:27017'
    networks: 
      - nodejs-network

networks: 
  nodejs-network: