version: "3"

services:
  app:
    container_name: nodejs-app
    build: .
    ports:
      - '3031:3000'
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  
  mongo:
    container_name: nodejs-mongodb
    image: mongo
    ports:
      - '27017:27017'